app = "tu-bot-discord"
primary_region = "mad"  # Madrid, cambia según tu región

[build]
  dockerfile = "Dockerfile"

[env]
  BOT_TOKEN = "tu-token"
  FLY = "true"  # Para identificar el entorno

[mounts]
  source = "empleados_data"
  destination = "/data"

[http_service]
  internal_port = 3000
  force_https = true