# fly.toml app configuration file generated for nexus-9kgjsq on 2025-04-28T11:03:30-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nexus-9kgjsq'
primary_region = 'iad'

[build]
  builder = 'heroku/builder:22'

[processes]
  app = ""  # Fuerza a Fly.io a mantener el proceso activo

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false  # Evita apagado automático
  auto_start_machines = true
  min_machines_running = 1    # Mínimo 1 instancia siempre activa

[vm]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

[[mounts]]
  source = 'data'
  destination = '/data'